//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BF1SuckerWV {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BF1SuckerWV.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;serverinstancerequest&gt;
        ///  &lt;blazesdkversion&gt;15.1.1.3.0&lt;/blazesdkversion&gt;
        ///  &lt;blazesdkbuilddate&gt;Jul 13 2018 21:54:46&lt;/blazesdkbuilddate&gt;
        ///  &lt;clientname&gt;tunguska client&lt;/clientname&gt;
        ///  &lt;clienttype&gt;CLIENT_TYPE_GAMEPLAY_USER&lt;/clienttype&gt;
        ///  &lt;clientplatform&gt;pc&lt;/clientplatform&gt;
        ///  &lt;clientskuid&gt;pc&lt;/clientskuid&gt;
        ///  &lt;clientversion&gt;XPack23779779retail-x64-1.0-3779779&lt;/clientversion&gt;
        ///  &lt;dirtysdkversion&gt;15.1.2.1.0&lt;/dirtysdkversion&gt;
        ///  &lt;environment&gt;prod&lt;/environment&gt;
        ///  &lt;clientlocale&gt;170172 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string RedirectorRequestBody {
            get {
                return ResourceManager.GetString("RedirectorRequestBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die POST /redirector/getServerInstance HTTP/1.1
        ///Host: winter15.gosredirector.ea.com:42230
        ///Content-Length: XXXX
        ///User-Agent: ProtoHttp 1.3/DS 15.1.2.1.0 (Windows)
        ///Content-Type: application/xml ähnelt.
        /// </summary>
        internal static string RedirectorRequestHeader {
            get {
                return ResourceManager.GetString("RedirectorRequestHeader", resourceCulture);
            }
        }
    }
}
